name: Run PHP Linter
on:
  pull_request:
    types:
      - opened
      - reopened
      - review_requested
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Composer install
        run: composer install
      - name: Check coding standards
        run: composer -n code-sniff